# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 06:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('mycenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('show_name', models.CharField(max_length=255, null=True, verbose_name='\u663e\u793a\u540d\u79f0')),
                ('avatar_path', models.CharField(max_length=255, null=True, verbose_name='\u5934\u50cf\u8def\u5f84')),
                ('telephone', models.CharField(max_length=255, null=True, verbose_name='\u7535\u8bdd')),
                ('auth_code', models.CharField(max_length=255, null=True, verbose_name='\u9a8c\u8bc1\u7801')),
                ('signatrue', models.CharField(max_length=255, null=True, verbose_name='\u7b7e\u540d')),
                ('send_date', models.DateTimeField(null=True, verbose_name='\u53d1\u9001\u65f6\u95f4')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mycenter.ImgMaterial', verbose_name='\u7528\u6237\u5934\u50cf')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SysMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, null=True, verbose_name=b'key')),
                ('value', models.TextField(null=True, verbose_name=b'value')),
                ('note', models.TextField(null=True, verbose_name='\u5907\u6ce8')),
                ('group', models.CharField(max_length=256, null=True, verbose_name=b'\xe5\x88\x86\xe7\xbb\x84')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'base_sys_material',
                'verbose_name': '\u7cfb\u7edf\u7d20\u6750\u8868',
                'verbose_name_plural': '\u7cfb\u7edf\u7d20\u6750\u8868',
            },
        ),
    ]
