# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telphone', models.IntegerField(db_index=True, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('code', models.IntegerField(db_index=True, null=True, verbose_name='\u9a8c\u8bc1\u7801')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'temp_tel_code',
                'verbose_name': '\u4e34\u65f6\u624b\u673a\u53f7\u9a8c\u8bc1\u7801\u8868',
                'verbose_name_plural': '\u4e34\u65f6\u624b\u673a\u53f7\u9a8c\u8bc1\u7801\u8868',
            },
        ),
    ]
