# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_temptelcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptelcode',
            name='telphone',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
