# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycenter', '0001_initial'),
        ('base', '0003_auto_20170503_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='home_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mycenter.ImgMaterial', verbose_name='\u4e3b\u9875\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='home_path',
            field=models.CharField(max_length=255, null=True, verbose_name='\u4e3b\u9875\u8def\u5f84'),
        ),
    ]
