# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170513_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='abstract',
            field=models.TextField(null=True, verbose_name='\u663e\u793a\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='sex',
            field=models.BooleanField(default=True, verbose_name='\u6027\u522b'),
        ),
    ]
