# Generated by Django 3.0.7 on 2020-06-30 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20170514_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='abstract',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='sysmaterial',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='sysmaterial',
            name='group',
            field=models.CharField(max_length=256, null=True, verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='sysmaterial',
            name='key',
            field=models.CharField(max_length=256, null=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='sysmaterial',
            name='value',
            field=models.TextField(null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='sysmaterial',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
