# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('like_count', models.IntegerField(default=0, null=True, verbose_name='\u70b9\u8d5e\u6570\u91cf')),
                ('parent_id', models.IntegerField(db_index=True, null=True, verbose_name='\u76ee\u6807id')),
                ('parent_type', models.CharField(db_index=True, max_length=256, null=True, verbose_name='\u76ee\u6807\u7c7b\u578b')),
                ('parent_comment', models.IntegerField(db_index=True, null=True, verbose_name='\u4e0a\u7ea7\u8bc4\u8bba')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe7\x9b\xae\xe6\xa0\x87\xe7\x94\xa8\xe6\x88\xb7id')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'base_comment',
                'verbose_name': '\u8bc4\u8bba\u8868',
                'verbose_name_plural': '\u8bc4\u8bba\u8868',
            },
        ),
        migrations.CreateModel(
            name='ForumSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u5206\u7c7b\u6807\u9898')),
                ('describe', models.TextField(null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
                ('source', models.CharField(max_length=256, null=True, verbose_name='\u6e90\u6570\u636e')),
                ('url', models.CharField(max_length=256, null=True, verbose_name='url')),
                ('icon', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u6807')),
                ('a_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'comm_forum_sort',
                'verbose_name': '\u8bba\u575b\u5206\u7c7b',
                'verbose_name_plural': '\u8bba\u575b\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='TopicReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(null=True, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('forum_sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community.ForumSort', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'db_table': 'comm_topic_review',
                'verbose_name': '\u8bc4\u8bba\u8868',
                'verbose_name_plural': '\u8bc4\u8bba\u8868',
            },
        ),
        migrations.CreateModel(
            name='TopicText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u4e3b\u9898')),
                ('text_txt', models.TextField(null=True, verbose_name='\u5185\u5bb9')),
                ('text_htm', models.TextField(null=True, verbose_name='\u5185\u5bb9\u4ee3\u7801\u6bb5')),
                ('u_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('a_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('priority', models.IntegerField(default=0, null=True, verbose_name='\u4f18\u5148\u7ea7')),
                ('pviews', models.IntegerField(default=0, null=True, verbose_name='\u9605\u8bfb\u91cf')),
                ('collection', models.IntegerField(default=0, null=True, verbose_name='\u6536\u85cf\u91cf')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('forum_sort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community.ForumSort', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe7\xa7\xb0')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'comm_topic_text',
                'verbose_name': '\u8bba\u575b\u5206\u7c7b',
                'verbose_name_plural': '\u8bba\u575b\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='topicreview',
            name='topic_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community.TopicText', verbose_name=b'\xe5\xb8\x96\xe5\xad\x90\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='topicreview',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba'),
        ),
    ]
