# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_guan_zhu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guan_zhu',
            old_name='topic_name',
            new_name='topic',
        ),
    ]
