# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_auto_20170423_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('gz_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x85\xb3\xe6\xb3\xa8\xe8\x80\x85')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community.Comment', verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x90\x8d\xe7\xa7\xb0')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'comm_collect_comment',
                'verbose_name': '\u8bc4\u8bba\u8868',
                'verbose_name_plural': '\u8bc4\u8bba\u8868',
            },
        ),
    ]
