# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_collectcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectcomment',
            old_name='gz_user',
            new_name='user',
        ),
    ]
