# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u6587\u4ef6\u540d')),
                ('alias', models.CharField(max_length=255, unique=True, verbose_name='\u5b9e\u9645\u4fdd\u5b58\u7684\u540d\u5b57')),
                ('describe', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u63cf\u8ff0')),
                ('old_path', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u5904\u7406\u524d\u7684\u8def\u5f84')),
                ('new_path', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u5904\u7406\u540e\u7684\u8def\u5f84')),
                ('file_size', models.CharField(max_length=256, null=True, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('downs', models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6b21\u6570')),
                ('source', models.CharField(max_length=256, null=True, verbose_name='\u6587\u4ef6\u6765\u6e90')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'img_material',
                'verbose_name': '\u56fe\u7247\u8bb0\u5f55',
                'verbose_name_plural': '\u56fe\u7247\u4fe1\u606f\u8868',
            },
        ),
    ]
