# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mycenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidebody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name=b'uuid')),
                ('s_title', models.CharField(max_length=256, null=True, verbose_name='\u6bb5\u843d\u6807\u9898')),
                ('s_body', models.TextField(null=True, verbose_name='\u6bb5\u843d\u6b63\u6587')),
                ('image_path', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u8def\u5f84')),
                ('image_name', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u540d\u79f0')),
                ('image_msg', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u8bf4\u660e')),
                ('image_location', models.CharField(max_length=256, null=True, verbose_name='\u4f4d\u7f6e')),
                ('image_explain', models.TextField(null=True, verbose_name='\u56fe\u7247\u63cf\u8ff0\u6b63\u6587')),
                ('numbers', models.IntegerField(null=True, verbose_name='\u6587\u7ae0\u5e8f\u53f7')),
                ('parent', models.IntegerField(null=True, verbose_name='\u4e0a\u4e00\u6761\u8bb0\u5f55')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
            ],
            options={
                'db_table': 'guide_document_body',
                'verbose_name': '\u6587\u6863\u5185\u5bb9',
                'verbose_name_plural': '\u6587\u6863\u8be6\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='GuideTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name=b'uuid')),
                ('title', models.CharField(default='\u672a\u547d\u540d\u8349\u7a3f', max_length=256, null=True, verbose_name='\u6807\u9898')),
                ('abstract', models.TextField(null=True, verbose_name='\u6458\u8981')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('source', models.CharField(max_length=256, null=True, verbose_name='\u6587\u7ae0\u6765\u6e90')),
                ('pviews', models.IntegerField(default=0, null=True, verbose_name='\u9605\u8bfb\u91cf')),
                ('collection', models.IntegerField(default=0, null=True, verbose_name='\u6536\u85cf\u91cf')),
                ('u_public', models.BooleanField(default=False, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('a_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('priority', models.IntegerField(default=0, verbose_name='\u4f18\u5148\u7ea7')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba')),
                ('title_ico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mycenter.ImgMaterial', verbose_name='\u6587\u7ae0\u6807\u9898\u56fe\u7684id')),
                ('title_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mycenter.ImgMaterial', verbose_name='\u6587\u7ae0\u6807\u9898\u56fe\u7684id')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba')),
            ],
            options={
                'db_table': 'guide_document_title',
                'verbose_name': '\u6587\u6863\u6807\u9898',
                'verbose_name_plural': '\u6587\u6863\u6807\u9898',
            },
        ),
        migrations.AddField(
            model_name='guidebody',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.GuideTitle', verbose_name='\u6587\u7ae0\u6807\u9898id'),
        ),
        migrations.AddField(
            model_name='guidebody',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xba\xba'),
        ),
    ]
